### ISSUE TITLE
Could you support varnish 4.x or 5.x ?

### ISSUE THREAD

**Issue by fortheday** [varnish/libvmod-shield#6]
Hello,
This mod what I wanted because there is no disconnect action on the varnish.
I installed varnish-cache 4.1.1
But I can't use this.
Do you have any plan to support 4.x or 5.x?
Thanks!

**Comment by narfeta** [comment]
We are using this vmod with varnish-4.1.3 without problems using the 4.1 branch

https://github.com/varnish/libvmod-shield/tree/4.1

Now we want to migrate to the 5.1 version but this vmod does not work with it.

+1 for supporting varnish 5.x

**Comment by lucaizzo** [comment]
If behind load balancer will it reset current connection only or all connections coming from the loadbalancer?

**Comment by mbgrydeland** [comment]
This vmod really is just a hack that was created mostly as an experiment. It managed to perform some tricks that happened to be OK the way the rest of the Varnish architecture was laid out in 3.x. For later Varnishes, the architecture has changed, and the hack probably wouldn't work any longer. Because of this, there are no plans to move this vmod to do the later Varnish releases.
